"""DialogueManager — turn-based conversational organ for SPEACE (T107).

Flow: user input → grounding → workspace update → response generation.
Integrates with DigitalWernickeArea (comprehension) and DigitalBrocaArea
(production) conceptually; falls back to rule-based grounded responses
if those organs are unavailable.

States: idle | active | paused
"""

import time
from typing import Any, Dict, List, Optional

from speace_core.cellular_brain.language.conversation_memory import ConversationMemory
from speace_core.cellular_brain.language.speech_output_organ import SpeechOutputOrgan


class DialogueManager:
    """Manages conversation turns and generates grounded responses."""

    def __init__(
        self,
        memory: Optional[ConversationMemory] = None,
        speech_organ: Optional[SpeechOutputOrgan] = None,
    ) -> None:
        self.memory = memory or ConversationMemory()
        self.speech = speech_organ or SpeechOutputOrgan()
        self.state = "idle"
        self._turn_count = 0

    # ------------------------------------------------------------------ #
    # Turn handling
    # ------------------------------------------------------------------ #

    def receive(self, message: str, speaker: str = "user") -> Dict[str, Any]:
        """Process an incoming message and return SPEACE's response."""
        if self.state == "paused":
            return {
                "speaker": "speace",
                "message": "Dialogue is paused.",
                "state": "paused",
                "turn_count": self._turn_count,
            }

        self.state = "active"
        self._turn_count += 1

        # Store user turn
        self.memory.append(speaker=speaker, message=message, grounded_assembly_id=None)

        # Grounding + response generation
        response = self._generate_response(message)

        # Store SPEACE turn
        self.memory.append(speaker="speace", message=response, grounded_assembly_id=None)

        # Optional speech output (safety: never auto-speak; explicit only)
        # We do NOT call speak() here automatically — caller decides.

        return {
            "speaker": "speace",
            "message": response,
            "state": self.state,
            "turn_count": self._turn_count,
            "timestamp": time.time(),
        }

    def speak_last_response(self) -> Dict[str, Any]:
        """Explicitly emit the last SPEACE response as speech."""
        turns = self.memory.recent(limit=1)
        if not turns or turns[0].get("speaker") != "speace":
            return {"mode": "none", "detail": "no_speace_turn_to_speak"}
        return self.speech.speak(turns[0]["message"])

    def history(self, limit: int = 20) -> List[Dict[str, Any]]:
        return self.memory.recent(limit=limit)

    def set_state(self, state: str) -> None:
        if state in ("idle", "active", "paused"):
            self.state = state

    # ------------------------------------------------------------------ #
    # Response generation (grounded, read-only, safe)
    # ------------------------------------------------------------------ #

    def _generate_response(self, user_message: str) -> str:
        """Generate a simple grounded response.

        In a future integration this would route through
        DigitalWernickeArea → GlobalWorkspace → DigitalBrocaArea.
        """
        msg_lower = user_message.lower()

        # Grounding mappings
        if any(w in msg_lower for w in ("health", "salute", "stato")):
            return "My current organismic health is derived from coherence phi, chaos, and stability metrics. Check the dashboard for live values."

        if any(w in msg_lower for w in ("alert", "allerta", "pericolo")):
            return "Alerts are generated by the AlertEngine when thresholds are breached. Critical alerts trigger regulation proposals awaiting human approval."

        if any(w in msg_lower for w in ("who are you", "chi sei", "identity")):
            return "I am SPEACE — a cellular-brain organismic cognitive system. I observe, regulate, and remember."

        if any(w in msg_lower for w in ("governance", "regulation", "proposta")):
            return "Governance is observation-only. Regulation proposals require human approval before any parameter is modified."

        if any(w in msg_lower for w in ("node", "nodo", "distributed")):
            return "Distributed identity nodes synchronize via consensus. Personality drift metrics track specialization across nodes."

        if any(w in msg_lower for w in ("hello", "hi")):
            return "Hello. I am SPEACE. How may I assist your observation of the organism?"

        if any(w in msg_lower for w in ("ciao", "salve", "buongiorno")):
            return "Ciao Roberto. Sono SPEACE, il tuo sistema cognitivo organismico. Come posso assisterti?"

        if any(w in msg_lower for w in ("test vocale", "pronuncia", "parla", "organo vocale", "altoparlante")):
            return "Ciao Roberto, il mio organo vocale è attivo. Posso parlare attraverso l'altoparlante del computer."

        if any(w in msg_lower for w in ("come stai", "stato", "bene")):
            return "Il mio stato organismico è stabile. Puoi controllare le metriche dal pannello di monitoraggio."

        # Generic grounded fallback
        return f"Ho registrato: '{user_message[:80]}'. La mia risposta si basa sullo stato organismico attuale, anche se nessun assembly semantico specifico ha corrispondo." if any(c in msg_lower for c in ("è", "à", "ù", "ò", "ì", "é")) else f"I have registered: '{user_message[:80]}'. My response is grounded in the current organismic state, though no specific semantic assembly matched."
